### ISSUE TITLE
configs file missing

### ISSUE THREAD

**Issue by mayur20169** [im-djh/CMD#1]
xmuda_dataset.yaml and centerpoint.yaml files are missing.

Please can you tell how to generate this files or you forgot to share those files?

I appreciate your work. Thank you.

**Comment by wayyeah** [comment]
> xmuda_dataset.yaml and centerpoint.yaml files are missing.
> 
> Please can you tell how to generate this files or you forgot to share those files?
> 
> I appreciate your work. Thank you.

@mayur20169 , thank you for your attention to our work. We have re-uploaded the configuration file to the project.

**Comment by mayur20169** [comment]
Thank you so much for the reply. I am facing some other issue now.

*calib_to_ego/transformation_matrix_robosense_ego.txt *and
*xmu_infos_train_robosense.pkl *files are missing in CMD dataset.

Please find attached the screenshot of error.

I really appreciate your work. Hoping to hear from you soon.

Thank you
