### ISSUE TITLE
calib_to_ego/transformation_matrix_robosense_ego.txt and xmu_infos_train_robosense.pkl not exists

### ISSUE THREAD

**Issue by mayur20169** [im-djh/CMD#2]
calib_to_ego/transformation_matrix_robosense_ego.txt and xmu_infos_train_robosense.pkl files are missing in CMD dataset.

Please can you tell how to generate this files or you forgot to share those files?

I appreciate your work. Thank you.

**Comment by mayur20169** [comment]
![Screenshot from 2024-09-30 10-44-32](https://github.com/user-attachments/assets/b0d5a9f5-9efe-473d-b975-3a857dbb91a8)

**Comment by mayur20169** [comment]
![Screenshot from 2024-09-30 11-23-24](https://github.com/user-attachments/assets/50820e7a-bdf1-41ae-a8fb-28f57ad1524a)

**Comment by wayyeah** [comment]
You can try to comment out the relevant code about ’calib’ and re-run to generate the pkl file. If it doesn't work, I will upload the relevant files tonight.@mayur20169

**Comment by wayyeah** [comment]
@mayur20169  We have now uploaded the files related to Calib to the download path of the dataset.
