### ISSUE TITLE
mmdetection3d support

### ISSUE THREAD

**Issue by TillBeemelmanns** [im-djh/CMD#6]
Hi! 
Thanks for this nice work and the dataset!

Are you planning to give mmdetection3d support ?

Best,
Till

**Comment by wayyeah** [comment]
> Hi! Thanks for this nice work and the dataset!
> 
> Are you planning to give mmdetection3d support ?
> 
> Best, Till

@TillBeemelmanns  
Thank you for your attention to our work. We currently have no plans to migrate to mmdetecion3d. You can try the migration yourself. In theory, just complete the migration of /pcdet/dataset/xmu/xmu_dataset.py.

**Comment by TillBeemelmanns** [comment]
Alright thanks for the information. Before I put work into the migration to mmdetection3d, I wanted to check, if you guys are not working on the same ;)
